package io.github.mtrevisan.familylegacy.v2.ui.components;


public enum PanelKey{
	INDIVIDUAL_ATTRIBUTE,
	GROUP_ATTRIBUTE,
	RELATIONSHIP_AS_SUBJECT, RELATIONSHIP_AS_OBJECT,
	PLACE_RELATIONSHIP_AS_SUBJECT, PLACE_RELATIONSHIP_AS_OBJECT,
	EVENT_PARTICIPATION_ON_PARTICIPANT, EVENT_PARTICIPATION_ON_EVENT,
	CONTEXT_IMPACT, CONTEXT_IMPACT_ON_TARGET, CONTEXT_IMPACT_ON_CONTEXT,
	CONCLUSION,
	IDENTITY_HYPOTHESIS,
	RESEARCH_QUESTION,
	RESEARCH_ACTIVITY_ON_QUESTION, RESEARCH_ACTIVITY_ON_SOURCE,
	RESEARCH_TASK,
	REPOSITORY,
	SOURCE, SOURCE_ON_REPOSITORY,
	DOCUMENT,
	NOTE,
	EVIDENCE,
	PRIVACY,
	AUDIT
}
