/**
 * Copyright (c) 2020 Mauro Trevisan
 * <p>
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 * <p>
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * <p>
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */
package io.github.mtrevisan.familylegacy.gedcom.transformations;

import io.github.mtrevisan.familylegacy.gedcom.Flef;
import io.github.mtrevisan.familylegacy.gedcom.Gedcom;
import io.github.mtrevisan.familylegacy.gedcom.GedcomNode;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;


class IndividualTransformationTest{

	private final Transformer transformerTo = new Transformer(Protocol.FLEF);
	private final Transformer transformerFrom = new Transformer(Protocol.GEDCOM);


	@Test
	void to(){
		final GedcomNode individual = transformerTo.create("INDI")
			.withID("I1")
			.addChildValue("RESN", "RESTRICTION_NOTICE")
			.addChild(transformerTo.create("NAME")
				.withValue("NAME_PERSONAL")
				.addChildValue("TYPE", "NAME_TYPE")
				.addChildValue("NPFX", "NAME_PIECE_PREFIX1")
				.addChildValue("GIVN", "NAME_PIECE_GIVEN1")
				.addChildValue("NICK", "NAME_PIECE_NICKNAME1")
				.addChildValue("SPFX", "NAME_PIECE_SURNAME_PREFIX1")
				.addChildValue("SURN", "NAME_PIECE_SURNAME1")
				.addChildValue("NSFX", "NAME_PIECE_SUFFIX1")
				.addChildReference("NOTE", "N-10")
				.addChildValue("NOTE", "SUBMITTER_TEXT10")
				.addChild(transformerTo.create("SOUR")
					.addChildValue("TEXT", "TEXT_FROM_SOURCE1")
					.addChildReference("OBJE", "D-1")
					.addChild(transformerTo.create("OBJE")
						.addChildValue("TITL", "DESCRIPTIVE_TITLE1")
						.addChild(transformerTo.create("FORM")
							.withValue("MULTIMEDIA_FORMAT7")
							.addChildValue("MEDI", "SOURCE_MEDIA_TYPE1")
						)
						.addChildValue("FILE", "MULTIMEDIA_FILE_REFN1")
					)
					.addChildReference("CULTURAL_RULE", "A1")
					.addChildReference("NOTE", "N-11")
					.addChildValue("NOTE", "SUBMITTER_TEXT11")
					.addChildValue("QUAY", "CERTAINTY_ASSESSMENT11")
				)
				.addChild(transformerTo.create("FONE")
					.withValue("NAME_PHONETIC_VARIATION")
					.addChildValue("TYPE", "PHONETIC_TYPE")
					.addChildValue("NPFX", "NAME_PIECE_PREFIX2")
					.addChildValue("GIVN", "NAME_PIECE_GIVEN2")
					.addChildValue("NICK", "NAME_PIECE_NICKNAME2")
					.addChildValue("SPFX", "NAME_PIECE_SURNAME_PREFIX2")
					.addChildValue("SURN", "NAME_PIECE_SURNAME2")
					.addChildValue("NSFX", "NAME_PIECE_SUFFIX2")
					.addChildReference("NOTE", "N-9")
					.addChildValue("NOTE", "SUBMITTER_TEXT9")
					.addChild(transformerTo.create("SOUR")
						.addChildValue("TEXT", "TEXT_FROM_SOURCE2")
						.addChildReference("OBJE", "D-2")
						.addChild(transformerTo.create("OBJE")
							.addChildValue("TITL", "DESCRIPTIVE_TITLE2")
							.addChild(transformerTo.create("FORM")
								.withValue("MULTIMEDIA_FORMAT2")
								.addChildValue("MEDI", "SOURCE_MEDIA_TYPE2")
							)
							.addChildValue("FILE", "MULTIMEDIA_FILE_REFN2")
						)
						.addChildReference("NOTE", "N-12")
						.addChildValue("NOTE", "SUBMITTER_TEXT12")
						.addChildValue("QUAY", "CERTAINTY_ASSESSMENT12")
					)
				)
				.addChild(transformerTo.create("ROMN")
					.withValue("NAME_ROMANIZED_VARIATION")
					.addChildValue("TYPE", "ROMANIZED_TYPE")
					.addChildValue("NPFX", "NAME_PIECE_PREFIX3")
					.addChildValue("GIVN", "NAME_PIECE_GIVEN3")
					.addChildValue("NICK", "NAME_PIECE_NICKNAME3")
					.addChildValue("SPFX", "NAME_PIECE_SURNAME_PREFIX3")
					.addChildValue("SURN", "NAME_PIECE_SURNAME3")
					.addChildValue("NSFX", "NAME_PIECE_SUFFIX3")
					.addChildReference("NOTE", "N-8")
					.addChildValue("NOTE", "SUBMITTER_TEXT8")
					.addChild(transformerTo.create("SOUR")
						.addChildValue("TEXT", "TEXT_FROM_SOURCE3")
						.addChildReference("OBJE", "D-3")
						.addChild(transformerTo.create("OBJE")
							.addChildValue("TITL", "DESCRIPTIVE_TITLE3")
							.addChild(transformerTo.create("FORM")
								.withValue("MULTIMEDIA_FORMAT3")
								.addChildValue("MEDI", "SOURCE_MEDIA_TYPE3")
							)
							.addChildValue("FILE", "MULTIMEDIA_FILE_REFN3")
						)
						.addChildReference("NOTE", "N-13")
						.addChildValue("NOTE", "SUBMITTER_TEXT13")
						.addChildValue("QUAY", "CERTAINTY_ASSESSMENT13")
					)
				)
			)
			.addChildValue("SEX", "SEX_VALUE")
			.addChild(transformerTo.create("BIRT")
				.addChildValue("TYPE", "EVENT_OR_FACT_CLASSIFICATION1")
				.addChildValue("DATE", "DATE_VALUE1")
				.addChild(transformerTo.create("PLAC")
					.addChildValue("FORM", "PLACE_HIERARCHY1")
					.addChild(transformerTo.create("FONE")
						.withValue("PLACE_PHONETIC_VARIATION1")
						.addChildValue("TYPE", "PHONETIC_TYPE")
					)
					.addChild(transformerTo.create("ROMN")
						.withValue("PLACE_ROMANIZED_VARIATION")
						.addChildValue("TYPE", "ROMANIZED_TYPE")
					)
					.addChild(transformerTo.create("MAP")
						.addChildValue("LATI", "PLACE_LATITUDE1")
						.addChildValue("LONG", "PLACE_LONGITUDE1")
					)
					.addChildReference("NOTE", "N-12")
				)
				.addChild(transformerTo.create("ADDR")
					.withValue("ADDRESS_LINE1")
					.addChildValue("CONT", "ADDRESS_LINE1")
					.addChildValue("ADR1", "ADDRESS_LINE11")
					.addChildValue("ADR2", "ADDRESS_LINE12")
					.addChildValue("ADR3", "ADDRESS_LINE13")
					.addChildValue("CITY", "ADDRESS_CITY1")
					.addChildValue("STAE", "ADDRESS_STATE1")
					.addChildValue("POST", "ADDRESS_POSTAL_CODE1")
					.addChildValue("CTRY", "ADDRESS_COUNTRY1")
				)
				.addChildValue("PHON", "PHONE_NUMBER1")
				.addChildValue("EMAIL", "ADDRESS_EMAIL1")
				.addChildValue("FAX", "ADDRESS_FAX1")
				.addChildValue("WWW", "ADDRESS_WEB_PAGE1")
				.addChildValue("AGNC", "RESPONSIBLE_AGENCY1")
				.addChildValue("RELI", "RELIGIOUS_AFFILIATION1")
				.addChildValue("CAUS", "CAUSE_OF_EVENT1")
				.addChildValue("RESN", "RESTRICTION_NOTICE1")
				.addChildReference("NOTE", "N-12")
				.addChildReference("SOUR", "S-4")
				.addChildReference("OBJE", "D-4")
				.addChildValue("AGE", "AGE_AT_EVENT")
				.addChildReference("FAMC", "F3")
			)
			.addChild(transformerTo.create("DEAT")
				.withValue("Y")
				.addChildValue("TYPE", "EVENT_OR_FACT_CLASSIFICATION2")
				.addChildValue("DATE", "DATE_VALUE2")
				.addChild(transformerTo.create("PLAC")
					.addChildValue("FORM", "PLACE_HIERARCHY1")
					.addChild(transformerTo.create("FONE")
						.withValue("PLACE_PHONETIC_VARIATION1")
						.addChildValue("TYPE", "PHONETIC_TYPE")
					)
					.addChild(transformerTo.create("ROMN")
						.withValue("PLACE_ROMANIZED_VARIATION")
						.addChildValue("TYPE", "ROMANIZED_TYPE")
					)
					.addChild(transformerTo.create("MAP")
						.addChildValue("LATI", "PLACE_LATITUDE2")
						.addChildValue("LONG", "PLACE_LONGITUDE2")
					)
					.addChildReference("NOTE", "N-12")
				)
				.addChild(transformerTo.create("ADDR")
					.withValue("ADDRESS_LINE2")
					.addChildValue("CONT", "ADDRESS_LINE2")
					.addChildValue("ADR1", "ADDRESS_LINE21")
					.addChildValue("ADR2", "ADDRESS_LINE22")
					.addChildValue("ADR3", "ADDRESS_LINE23")
					.addChildValue("CITY", "ADDRESS_CITY2")
					.addChildValue("STAE", "ADDRESS_STATE2")
					.addChildValue("POST", "ADDRESS_POSTAL_CODE2")
					.addChildValue("CTRY", "ADDRESS_COUNTRY2")
				)
				.addChildValue("PHON", "PHONE_NUMBER2")
				.addChildValue("EMAIL", "ADDRESS_EMAIL2")
				.addChildValue("FAX", "ADDRESS_FAX2")
				.addChildValue("WWW", "ADDRESS_WEB_PAGE2")
				.addChildValue("AGNC", "RESPONSIBLE_AGENCY2")
				.addChildValue("RELI", "RELIGIOUS_AFFILIATION2")
				.addChildValue("CAUS", "CAUSE_OF_EVENT2")
				.addChildValue("RESN", "RESTRICTION_NOTICE2")
				.addChildReference("NOTE", "N-13")
				.addChildReference("SOUR", "S-5")
				.addChildReference("OBJE", "D-5")
				.addChildValue("AGE", "AGE_AT_EVENT")
			)
			.addChild(transformerTo.create("BURI")
				.addChildValue("TYPE", "EVENT_OR_FACT_CLASSIFICATION3")
				.addChildValue("DATE", "DATE_VALUE3")
				.addChild(transformerTo.create("PLAC")
					.addChildValue("FORM", "PLACE_HIERARCHY1")
					.addChild(transformerTo.create("FONE")
						.withValue("PLACE_PHONETIC_VARIATION1")
						.addChildValue("TYPE", "PHONETIC_TYPE")
					)
					.addChild(transformerTo.create("ROMN")
						.withValue("PLACE_ROMANIZED_VARIATION")
						.addChildValue("TYPE", "ROMANIZED_TYPE")
					)
					.addChild(transformerTo.create("MAP")
						.addChildValue("LATI", "PLACE_LATITUDE3")
						.addChildValue("LONG", "PLACE_LONGITUDE3")
					)
					.addChildReference("NOTE", "N-12")
				)
				.addChild(transformerTo.create("ADDR")
					.withValue("ADDRESS_LINE3")
					.addChildValue("CONT", "ADDRESS_LINE3")
					.addChildValue("ADR1", "ADDRESS_LINE31")
					.addChildValue("ADR2", "ADDRESS_LINE32")
					.addChildValue("ADR3", "ADDRESS_LINE33")
					.addChildValue("CITY", "ADDRESS_CITY3")
					.addChildValue("STAE", "ADDRESS_STATE3")
					.addChildValue("POST", "ADDRESS_POSTAL_CODE3")
					.addChildValue("CTRY", "ADDRESS_COUNTRY3")
				)
				.addChildValue("PHON", "PHONE_NUMBER3")
				.addChildValue("EMAIL", "ADDRESS_EMAIL3")
				.addChildValue("FAX", "ADDRESS_FAX3")
				.addChildValue("WWW", "ADDRESS_WEB_PAGE3")
				.addChildValue("AGNC", "RESPONSIBLE_AGENCY3")
				.addChildValue("RELI", "RELIGIOUS_AFFILIATION3")
				.addChildValue("CAUS", "CAUSE_OF_EVENT3")
				.addChildValue("RESN", "RESTRICTION_NOTICE3")
				.addChildReference("NOTE", "N-13")
				.addChildReference("SOUR", "S-6")
				.addChildReference("OBJE", "D-6")
				.addChildValue("AGE", "AGE_AT_EVENT")
			)
			.addChild(transformerTo.create("ADOP")
				.addChildValue("TYPE", "EVENT_OR_FACT_CLASSIFICATION4")
				.addChildValue("DATE", "DATE_VALUE4")
				.addChild(transformerTo.create("PLAC")
					.addChildValue("FORM", "PLACE_HIERARCHY1")
					.addChild(transformerTo.create("FONE")
						.withValue("PLACE_PHONETIC_VARIATION1")
						.addChildValue("TYPE", "PHONETIC_TYPE")
					)
					.addChild(transformerTo.create("ROMN")
						.withValue("PLACE_ROMANIZED_VARIATION")
						.addChildValue("TYPE", "ROMANIZED_TYPE")
					)
					.addChild(transformerTo.create("MAP")
						.addChildValue("LATI", "PLACE_LATITUDE4")
						.addChildValue("LONG", "PLACE_LONGITUDE4")
					)
					.addChildReference("NOTE", "N-12")
				)
				.addChild(transformerTo.create("ADDR")
					.withValue("ADDRESS_LINE4")
					.addChildValue("CONT", "ADDRESS_LINE4")
					.addChildValue("ADR1", "ADDRESS_LINE41")
					.addChildValue("ADR2", "ADDRESS_LINE42")
					.addChildValue("ADR3", "ADDRESS_LINE43")
					.addChildValue("CITY", "ADDRESS_CITY4")
					.addChildValue("STAE", "ADDRESS_STATE4")
					.addChildValue("POST", "ADDRESS_POSTAL_CODE4")
					.addChildValue("CTRY", "ADDRESS_COUNTRY4")
				)
				.addChildValue("PHON", "PHONE_NUMBER4")
				.addChildValue("EMAIL", "ADDRESS_EMAIL4")
				.addChildValue("FAX", "ADDRESS_FAX4")
				.addChildValue("WWW", "ADDRESS_WEB_PAGE4")
				.addChildValue("AGNC", "RESPONSIBLE_AGENCY4")
				.addChildValue("RELI", "RELIGIOUS_AFFILIATION4")
				.addChildValue("CAUS", "CAUSE_OF_EVENT4")
				.addChildValue("RESN", "RESTRICTION_NOTICE4")
				.addChildReference("NOTE", "N-12")
				.addChildReference("SOUR", "S-7")
				.addChildReference("OBJE", "D-7")
				.addChildValue("AGE", "AGE_AT_EVENT")
				.addChild(transformerTo.create("FAMC")
					.withXRef("F4")
					.addChildValue("ADOP", "ADOPTED_BY_WHICH_PARENT")
				)
			)
			.addChild(transformerTo.create("DSCR")
				.withValue("CHARACTERISTIC")
				.addChildValue("TYPE", "EVENT_OR_FACT_CLASSIFICATION5")
				.addChildValue("DATE", "DATE_VALUE5")
				.addChild(transformerTo.create("PLAC")
					.addChildValue("FORM", "PLACE_HIERARCHY1")
					.addChild(transformerTo.create("FONE")
						.withValue("PLACE_PHONETIC_VARIATION1")
						.addChildValue("TYPE", "PHONETIC_TYPE")
					)
					.addChild(transformerTo.create("ROMN")
						.withValue("PLACE_ROMANIZED_VARIATION")
						.addChildValue("TYPE", "ROMANIZED_TYPE")
					)
					.addChild(transformerTo.create("MAP")
						.addChildValue("LATI", "PLACE_LATITUDE5")
						.addChildValue("LONG", "PLACE_LONGITUDE5")
					)
					.addChildReference("NOTE", "N-12")
				)
				.addChild(transformerTo.create("ADDR")
					.withValue("ADDRESS_LINE5")
					.addChildValue("CONT", "ADDRESS_LINE5")
					.addChildValue("ADR1", "ADDRESS_LINE51")
					.addChildValue("ADR2", "ADDRESS_LINE52")
					.addChildValue("ADR3", "ADDRESS_LINE53")
					.addChildValue("CITY", "ADDRESS_CITY5")
					.addChildValue("STAE", "ADDRESS_STATE5")
					.addChildValue("POST", "ADDRESS_POSTAL_CODE5")
					.addChildValue("CTRY", "ADDRESS_COUNTRY5")
				)
				.addChildValue("PHON", "PHONE_NUMBER5")
				.addChildValue("EMAIL", "ADDRESS_EMAIL5")
				.addChildValue("FAX", "ADDRESS_FAX5")
				.addChildValue("WWW", "ADDRESS_WEB_PAGE5")
				.addChildValue("AGNC", "RESPONSIBLE_AGENCY5")
				.addChildValue("RELI", "RELIGIOUS_AFFILIATION5")
				.addChildValue("CAUS", "CAUSE_OF_EVENT5")
				.addChildValue("RESN", "RESTRICTION_NOTICE5")
				.addChildReference("NOTE", "N-12")
				.addChildReference("SOUR", "S-8")
				.addChildReference("OBJE", "D-8")
				.addChildValue("AGE", "AGE_AT_EVENT")
			)
			.addChild(transformerTo.create("RESI")
				.addChildValue("TYPE", "EVENT_OR_FACT_CLASSIFICATION6")
				.addChildValue("DATE", "DATE_VALUE6")
			)
			.addChild(transformerTo.create("FAMC")
				.withXRef("F2")
				.addChildValue("PEDI", "PEDIGREE_LINKAGE_TYPE")
				.addChildValue("STAT", "CHILD_LINKAGE_STATUS")
				.addChildReference("NOTE", "N-8")
				.addChildValue("NOTE", "SUBMITTER_TEXT8")
			)
			.addChild(transformerTo.create("FAMS")
				.withValue("F1")
				.addChildReference("NOTE", "N-7")
				.addChildValue("NOTE", "SUBMITTER_TEXT7")
			)
			.addChildReference("SUBM", "SUBM1")
			.addChild(transformerTo.create("ASSO")
				.withXRef("I4")
				.addChildValue("RELA", "RELATION_IS_DESCRIPTOR")
				.addChild(transformerTo.create("SOUR")
					.withXRef("S-1")
					.addChildValue("PAGE", "WHERE_WITHIN_SOURCE")
					.addChild(transformerTo.create("EVEN")
						.withValue("EVENT_TYPE_CITED_FROM")
						.addChildValue("ROLE", "ROLE_IN_EVENT")
					)
					.addChild(transformerTo.create("DATA")
						.addChildValue("DATE", "ENTRY_RECORDING_DATE")
						.addChildValue("TEXT", "TEXT_FROM_SOURCE")
					)
					.addChildReference("OBJE", "D-9")
					.addChild(transformerTo.create("OBJE")
						.addChildValue("TITL", "DESCRIPTIVE_TITLE3")
						.addChild(transformerTo.create("FORM")
							.withValue("MULTIMEDIA_FORMAT3")
							.addChildValue("MEDI", "SOURCE_MEDIA_TYPE3")
						)
						.addChildValue("FILE", "MULTIMEDIA_FILE_REFN3")
					)
					.addChildReference("NOTE", "N-5")
					.addChildValue("NOTE", "SUBMITTER_TEXT5")
					.addChildValue("QUAY", "CERTAINTY_ASSESSMENT5")
				)
				.addChild(transformerTo.create("SOUR")
					.addChildValue("TEXT", "TEXT_FROM_SOURCE9")
					.addChildReference("OBJE", "D-10")
					.addChild(transformerTo.create("OBJE")
						.addChildValue("TITL", "DESCRIPTIVE_TITLE4")
						.addChild(transformerTo.create("FORM")
							.withValue("MULTIMEDIA_FORMAT4")
							.addChildValue("MEDI", "SOURCE_MEDIA_TYPE4")
						)
						.addChildValue("FILE", "MULTIMEDIA_FILE_REFN4")
					)
					.addChildReference("NOTE", "N-6")
					.addChildValue("NOTE", "SUBMITTER_TEXT6")
					.addChildValue("QUAY", "CERTAINTY_ASSESSMENT6")
				)
				.addChildReference("NOTE", "N-4")
				.addChildValue("NOTE", "SUBMITTER_TEXT4")
			)
			.addChildReference("ALIA", "I2")
			.addChildReference("ALIA", "I3")
			.addChildReference("NOTE", "N-3")
			.addChildValue("NOTE", "SUBMITTER_TEXT3")
			.addChild(transformerTo.create("SOUR")
				.withXRef("S-2")
				.addChildValue("PAGE", "WHERE_WITHIN_SOURCE")
				.addChild(transformerTo.create("EVEN")
					.withValue("EVENT_TYPE_CITED_FROM")
					.addChildValue("ROLE", "ROLE_IN_EVENT")
				)
				.addChild(transformerTo.create("DATA")
					.addChildValue("DATE", "ENTRY_RECORDING_DATE")
					.addChildValue("TEXT", "TEXT_FROM_SOURCE")
				)
				.addChildReference("OBJE", "D-11")
				.addChild(transformerTo.create("OBJE")
					.addChildValue("TITL", "DESCRIPTIVE_TITLE2")
					.addChild(transformerTo.create("FORM")
						.withValue("MULTIMEDIA_FORMAT2")
						.addChildValue("MEDI", "SOURCE_MEDIA_TYPE2")
					)
					.addChildValue("FILE", "MULTIMEDIA_FILE_REFN2")
				)
				.addChildReference("NOTE", "N-1")
				.addChildValue("NOTE", "SUBMITTER_TEXT1")
				.addChildValue("QUAY", "CERTAINTY_ASSESSMENT-2")
			)
			.addChild(transformerTo.create("SOUR")
				.addChildValue("TEXT", "TEXT_FROM_SOURCE10")
				.addChildReference("OBJE", "D-12")
				.addChild(transformerTo.create("OBJE")
					.addChildValue("TITL", "DESCRIPTIVE_TITLE3")
					.addChild(transformerTo.create("FORM")
						.withValue("MULTIMEDIA_FORMAT3")
						.addChildValue("MEDI", "SOURCE_MEDIA_TYPE3")
					)
					.addChildValue("FILE", "MULTIMEDIA_FILE_REFN3")
				)
				.addChildReference("NOTE", "N-2")
				.addChildValue("NOTE", "SUBMITTER_TEXT2")
				.addChildValue("QUAY", "CERTAINTY_ASSESSMENT-12")
			)
			.addChildReference("OBJE", "D-13")
			.addChild(transformerTo.create("OBJE")
				.addChildValue("TITL", "DESCRIPTIVE_TITLE1")
				.addChild(transformerTo.create("FORM")
					.withValue("MULTIMEDIA_FORMAT1")
					.addChildValue("MEDI", "SOURCE_MEDIA_TYPE1")
				)
				.addChildValue("FILE", "MULTIMEDIA_FILE_REFN1")
			);
		final Gedcom origin = new Gedcom();
		origin.addIndividual(individual);
		final Flef destination = new Flef();

		Assertions.assertEquals("id: I1, tag: INDI, children: [{tag: RESN, value: RESTRICTION_NOTICE}, {tag: NAME, value: NAME_PERSONAL, children: [{tag: TYPE, value: NAME_TYPE}, {tag: NPFX, value: NAME_PIECE_PREFIX1}, {tag: GIVN, value: NAME_PIECE_GIVEN1}, {tag: NICK, value: NAME_PIECE_NICKNAME1}, {tag: SPFX, value: NAME_PIECE_SURNAME_PREFIX1}, {tag: SURN, value: NAME_PIECE_SURNAME1}, {tag: NSFX, value: NAME_PIECE_SUFFIX1}, {tag: NOTE, ref: N-10}, {tag: NOTE, value: SUBMITTER_TEXT10}, {tag: SOUR, children: [{tag: TEXT, value: TEXT_FROM_SOURCE1}, {tag: OBJE, ref: D-1}, {tag: OBJE, children: [{tag: TITL, value: DESCRIPTIVE_TITLE1}, {tag: FORM, value: MULTIMEDIA_FORMAT7, children: [{tag: MEDI, value: SOURCE_MEDIA_TYPE1}]}, {tag: FILE, value: MULTIMEDIA_FILE_REFN1}]}, {tag: CULTURAL_RULE, ref: A1}, {tag: NOTE, ref: N-11}, {tag: NOTE, value: SUBMITTER_TEXT11}, {tag: QUAY, value: CERTAINTY_ASSESSMENT11}]}, {tag: FONE, value: NAME_PHONETIC_VARIATION, children: [{tag: TYPE, value: PHONETIC_TYPE}, {tag: NPFX, value: NAME_PIECE_PREFIX2}, {tag: GIVN, value: NAME_PIECE_GIVEN2}, {tag: NICK, value: NAME_PIECE_NICKNAME2}, {tag: SPFX, value: NAME_PIECE_SURNAME_PREFIX2}, {tag: SURN, value: NAME_PIECE_SURNAME2}, {tag: NSFX, value: NAME_PIECE_SUFFIX2}, {tag: NOTE, ref: N-9}, {tag: NOTE, value: SUBMITTER_TEXT9}, {tag: SOUR, children: [{tag: TEXT, value: TEXT_FROM_SOURCE2}, {tag: OBJE, ref: D-2}, {tag: OBJE, children: [{tag: TITL, value: DESCRIPTIVE_TITLE2}, {tag: FORM, value: MULTIMEDIA_FORMAT2, children: [{tag: MEDI, value: SOURCE_MEDIA_TYPE2}]}, {tag: FILE, value: MULTIMEDIA_FILE_REFN2}]}, {tag: NOTE, ref: N-12}, {tag: NOTE, value: SUBMITTER_TEXT12}, {tag: QUAY, value: CERTAINTY_ASSESSMENT12}]}]}, {tag: ROMN, value: NAME_ROMANIZED_VARIATION, children: [{tag: TYPE, value: ROMANIZED_TYPE}, {tag: NPFX, value: NAME_PIECE_PREFIX3}, {tag: GIVN, value: NAME_PIECE_GIVEN3}, {tag: NICK, value: NAME_PIECE_NICKNAME3}, {tag: SPFX, value: NAME_PIECE_SURNAME_PREFIX3}, {tag: SURN, value: NAME_PIECE_SURNAME3}, {tag: NSFX, value: NAME_PIECE_SUFFIX3}, {tag: NOTE, ref: N-8}, {tag: NOTE, value: SUBMITTER_TEXT8}, {tag: SOUR, children: [{tag: TEXT, value: TEXT_FROM_SOURCE3}, {tag: OBJE, ref: D-3}, {tag: OBJE, children: [{tag: TITL, value: DESCRIPTIVE_TITLE3}, {tag: FORM, value: MULTIMEDIA_FORMAT3, children: [{tag: MEDI, value: SOURCE_MEDIA_TYPE3}]}, {tag: FILE, value: MULTIMEDIA_FILE_REFN3}]}, {tag: NOTE, ref: N-13}, {tag: NOTE, value: SUBMITTER_TEXT13}, {tag: QUAY, value: CERTAINTY_ASSESSMENT13}]}]}]}, {tag: SEX, value: SEX_VALUE}, {tag: BIRT, children: [{tag: TYPE, value: EVENT_OR_FACT_CLASSIFICATION1}, {tag: DATE, value: DATE_VALUE1}, {tag: PLAC, children: [{tag: FORM, value: PLACE_HIERARCHY1}, {tag: FONE, value: PLACE_PHONETIC_VARIATION1, children: [{tag: TYPE, value: PHONETIC_TYPE}]}, {tag: ROMN, value: PLACE_ROMANIZED_VARIATION, children: [{tag: TYPE, value: ROMANIZED_TYPE}]}, {tag: MAP, children: [{tag: LATI, value: PLACE_LATITUDE1}, {tag: LONG, value: PLACE_LONGITUDE1}]}, {tag: NOTE, ref: N-12}]}, {tag: ADDR, value: ADDRESS_LINE1, children: [{tag: CONT, value: ADDRESS_LINE1}, {tag: ADR1, value: ADDRESS_LINE11}, {tag: ADR2, value: ADDRESS_LINE12}, {tag: ADR3, value: ADDRESS_LINE13}, {tag: CITY, value: ADDRESS_CITY1}, {tag: STAE, value: ADDRESS_STATE1}, {tag: POST, value: ADDRESS_POSTAL_CODE1}, {tag: CTRY, value: ADDRESS_COUNTRY1}]}, {tag: PHON, value: PHONE_NUMBER1}, {tag: EMAIL, value: ADDRESS_EMAIL1}, {tag: FAX, value: ADDRESS_FAX1}, {tag: WWW, value: ADDRESS_WEB_PAGE1}, {tag: AGNC, value: RESPONSIBLE_AGENCY1}, {tag: RELI, value: RELIGIOUS_AFFILIATION1}, {tag: CAUS, value: CAUSE_OF_EVENT1}, {tag: RESN, value: RESTRICTION_NOTICE1}, {tag: NOTE, ref: N-12}, {tag: SOUR, ref: S-4}, {tag: OBJE, ref: D-4}, {tag: AGE, value: AGE_AT_EVENT}, {tag: FAMC, ref: F3}]}, {tag: DEAT, value: Y, children: [{tag: TYPE, value: EVENT_OR_FACT_CLASSIFICATION2}, {tag: DATE, value: DATE_VALUE2}, {tag: PLAC, children: [{tag: FORM, value: PLACE_HIERARCHY1}, {tag: FONE, value: PLACE_PHONETIC_VARIATION1, children: [{tag: TYPE, value: PHONETIC_TYPE}]}, {tag: ROMN, value: PLACE_ROMANIZED_VARIATION, children: [{tag: TYPE, value: ROMANIZED_TYPE}]}, {tag: MAP, children: [{tag: LATI, value: PLACE_LATITUDE2}, {tag: LONG, value: PLACE_LONGITUDE2}]}, {tag: NOTE, ref: N-12}]}, {tag: ADDR, value: ADDRESS_LINE2, children: [{tag: CONT, value: ADDRESS_LINE2}, {tag: ADR1, value: ADDRESS_LINE21}, {tag: ADR2, value: ADDRESS_LINE22}, {tag: ADR3, value: ADDRESS_LINE23}, {tag: CITY, value: ADDRESS_CITY2}, {tag: STAE, value: ADDRESS_STATE2}, {tag: POST, value: ADDRESS_POSTAL_CODE2}, {tag: CTRY, value: ADDRESS_COUNTRY2}]}, {tag: PHON, value: PHONE_NUMBER2}, {tag: EMAIL, value: ADDRESS_EMAIL2}, {tag: FAX, value: ADDRESS_FAX2}, {tag: WWW, value: ADDRESS_WEB_PAGE2}, {tag: AGNC, value: RESPONSIBLE_AGENCY2}, {tag: RELI, value: RELIGIOUS_AFFILIATION2}, {tag: CAUS, value: CAUSE_OF_EVENT2}, {tag: RESN, value: RESTRICTION_NOTICE2}, {tag: NOTE, ref: N-13}, {tag: SOUR, ref: S-5}, {tag: OBJE, ref: D-5}, {tag: AGE, value: AGE_AT_EVENT}]}, {tag: BURI, children: [{tag: TYPE, value: EVENT_OR_FACT_CLASSIFICATION3}, {tag: DATE, value: DATE_VALUE3}, {tag: PLAC, children: [{tag: FORM, value: PLACE_HIERARCHY1}, {tag: FONE, value: PLACE_PHONETIC_VARIATION1, children: [{tag: TYPE, value: PHONETIC_TYPE}]}, {tag: ROMN, value: PLACE_ROMANIZED_VARIATION, children: [{tag: TYPE, value: ROMANIZED_TYPE}]}, {tag: MAP, children: [{tag: LATI, value: PLACE_LATITUDE3}, {tag: LONG, value: PLACE_LONGITUDE3}]}, {tag: NOTE, ref: N-12}]}, {tag: ADDR, value: ADDRESS_LINE3, children: [{tag: CONT, value: ADDRESS_LINE3}, {tag: ADR1, value: ADDRESS_LINE31}, {tag: ADR2, value: ADDRESS_LINE32}, {tag: ADR3, value: ADDRESS_LINE33}, {tag: CITY, value: ADDRESS_CITY3}, {tag: STAE, value: ADDRESS_STATE3}, {tag: POST, value: ADDRESS_POSTAL_CODE3}, {tag: CTRY, value: ADDRESS_COUNTRY3}]}, {tag: PHON, value: PHONE_NUMBER3}, {tag: EMAIL, value: ADDRESS_EMAIL3}, {tag: FAX, value: ADDRESS_FAX3}, {tag: WWW, value: ADDRESS_WEB_PAGE3}, {tag: AGNC, value: RESPONSIBLE_AGENCY3}, {tag: RELI, value: RELIGIOUS_AFFILIATION3}, {tag: CAUS, value: CAUSE_OF_EVENT3}, {tag: RESN, value: RESTRICTION_NOTICE3}, {tag: NOTE, ref: N-13}, {tag: SOUR, ref: S-6}, {tag: OBJE, ref: D-6}, {tag: AGE, value: AGE_AT_EVENT}]}, {tag: ADOP, children: [{tag: TYPE, value: EVENT_OR_FACT_CLASSIFICATION4}, {tag: DATE, value: DATE_VALUE4}, {tag: PLAC, children: [{tag: FORM, value: PLACE_HIERARCHY1}, {tag: FONE, value: PLACE_PHONETIC_VARIATION1, children: [{tag: TYPE, value: PHONETIC_TYPE}]}, {tag: ROMN, value: PLACE_ROMANIZED_VARIATION, children: [{tag: TYPE, value: ROMANIZED_TYPE}]}, {tag: MAP, children: [{tag: LATI, value: PLACE_LATITUDE4}, {tag: LONG, value: PLACE_LONGITUDE4}]}, {tag: NOTE, ref: N-12}]}, {tag: ADDR, value: ADDRESS_LINE4, children: [{tag: CONT, value: ADDRESS_LINE4}, {tag: ADR1, value: ADDRESS_LINE41}, {tag: ADR2, value: ADDRESS_LINE42}, {tag: ADR3, value: ADDRESS_LINE43}, {tag: CITY, value: ADDRESS_CITY4}, {tag: STAE, value: ADDRESS_STATE4}, {tag: POST, value: ADDRESS_POSTAL_CODE4}, {tag: CTRY, value: ADDRESS_COUNTRY4}]}, {tag: PHON, value: PHONE_NUMBER4}, {tag: EMAIL, value: ADDRESS_EMAIL4}, {tag: FAX, value: ADDRESS_FAX4}, {tag: WWW, value: ADDRESS_WEB_PAGE4}, {tag: AGNC, value: RESPONSIBLE_AGENCY4}, {tag: RELI, value: RELIGIOUS_AFFILIATION4}, {tag: CAUS, value: CAUSE_OF_EVENT4}, {tag: RESN, value: RESTRICTION_NOTICE4}, {tag: NOTE, ref: N-12}, {tag: SOUR, ref: S-7}, {tag: OBJE, ref: D-7}, {tag: AGE, value: AGE_AT_EVENT}, {tag: FAMC, ref: F4, children: [{tag: ADOP, value: ADOPTED_BY_WHICH_PARENT}]}]}, {tag: DSCR, value: CHARACTERISTIC, children: [{tag: TYPE, value: EVENT_OR_FACT_CLASSIFICATION5}, {tag: DATE, value: DATE_VALUE5}, {tag: PLAC, children: [{tag: FORM, value: PLACE_HIERARCHY1}, {tag: FONE, value: PLACE_PHONETIC_VARIATION1, children: [{tag: TYPE, value: PHONETIC_TYPE}]}, {tag: ROMN, value: PLACE_ROMANIZED_VARIATION, children: [{tag: TYPE, value: ROMANIZED_TYPE}]}, {tag: MAP, children: [{tag: LATI, value: PLACE_LATITUDE5}, {tag: LONG, value: PLACE_LONGITUDE5}]}, {tag: NOTE, ref: N-12}]}, {tag: ADDR, value: ADDRESS_LINE5, children: [{tag: CONT, value: ADDRESS_LINE5}, {tag: ADR1, value: ADDRESS_LINE51}, {tag: ADR2, value: ADDRESS_LINE52}, {tag: ADR3, value: ADDRESS_LINE53}, {tag: CITY, value: ADDRESS_CITY5}, {tag: STAE, value: ADDRESS_STATE5}, {tag: POST, value: ADDRESS_POSTAL_CODE5}, {tag: CTRY, value: ADDRESS_COUNTRY5}]}, {tag: PHON, value: PHONE_NUMBER5}, {tag: EMAIL, value: ADDRESS_EMAIL5}, {tag: FAX, value: ADDRESS_FAX5}, {tag: WWW, value: ADDRESS_WEB_PAGE5}, {tag: AGNC, value: RESPONSIBLE_AGENCY5}, {tag: RELI, value: RELIGIOUS_AFFILIATION5}, {tag: CAUS, value: CAUSE_OF_EVENT5}, {tag: RESN, value: RESTRICTION_NOTICE5}, {tag: NOTE, ref: N-12}, {tag: SOUR, ref: S-8}, {tag: OBJE, ref: D-8}, {tag: AGE, value: AGE_AT_EVENT}]}, {tag: RESI, children: [{tag: TYPE, value: EVENT_OR_FACT_CLASSIFICATION6}, {tag: DATE, value: DATE_VALUE6}]}, {tag: FAMC, ref: F2, children: [{tag: PEDI, value: PEDIGREE_LINKAGE_TYPE}, {tag: STAT, value: CHILD_LINKAGE_STATUS}, {tag: NOTE, ref: N-8}, {tag: NOTE, value: SUBMITTER_TEXT8}]}, {tag: FAMS, value: F1, children: [{tag: NOTE, ref: N-7}, {tag: NOTE, value: SUBMITTER_TEXT7}]}, {tag: SUBM, ref: SUBM1}, {tag: ASSO, ref: I4, children: [{tag: RELA, value: RELATION_IS_DESCRIPTOR}, {tag: SOUR, ref: S-1, children: [{tag: PAGE, value: WHERE_WITHIN_SOURCE}, {tag: EVEN, value: EVENT_TYPE_CITED_FROM, children: [{tag: ROLE, value: ROLE_IN_EVENT}]}, {tag: DATA, children: [{tag: DATE, value: ENTRY_RECORDING_DATE}, {tag: TEXT, value: TEXT_FROM_SOURCE}]}, {tag: OBJE, ref: D-9}, {tag: OBJE, children: [{tag: TITL, value: DESCRIPTIVE_TITLE3}, {tag: FORM, value: MULTIMEDIA_FORMAT3, children: [{tag: MEDI, value: SOURCE_MEDIA_TYPE3}]}, {tag: FILE, value: MULTIMEDIA_FILE_REFN3}]}, {tag: NOTE, ref: N-5}, {tag: NOTE, value: SUBMITTER_TEXT5}, {tag: QUAY, value: CERTAINTY_ASSESSMENT5}]}, {tag: SOUR, children: [{tag: TEXT, value: TEXT_FROM_SOURCE9}, {tag: OBJE, ref: D-10}, {tag: OBJE, children: [{tag: TITL, value: DESCRIPTIVE_TITLE4}, {tag: FORM, value: MULTIMEDIA_FORMAT4, children: [{tag: MEDI, value: SOURCE_MEDIA_TYPE4}]}, {tag: FILE, value: MULTIMEDIA_FILE_REFN4}]}, {tag: NOTE, ref: N-6}, {tag: NOTE, value: SUBMITTER_TEXT6}, {tag: QUAY, value: CERTAINTY_ASSESSMENT6}]}, {tag: NOTE, ref: N-4}, {tag: NOTE, value: SUBMITTER_TEXT4}]}, {tag: ALIA, ref: I2}, {tag: ALIA, ref: I3}, {tag: NOTE, ref: N-3}, {tag: NOTE, value: SUBMITTER_TEXT3}, {tag: SOUR, ref: S-2, children: [{tag: PAGE, value: WHERE_WITHIN_SOURCE}, {tag: EVEN, value: EVENT_TYPE_CITED_FROM, children: [{tag: ROLE, value: ROLE_IN_EVENT}]}, {tag: DATA, children: [{tag: DATE, value: ENTRY_RECORDING_DATE}, {tag: TEXT, value: TEXT_FROM_SOURCE}]}, {tag: OBJE, ref: D-11}, {tag: OBJE, children: [{tag: TITL, value: DESCRIPTIVE_TITLE2}, {tag: FORM, value: MULTIMEDIA_FORMAT2, children: [{tag: MEDI, value: SOURCE_MEDIA_TYPE2}]}, {tag: FILE, value: MULTIMEDIA_FILE_REFN2}]}, {tag: NOTE, ref: N-1}, {tag: NOTE, value: SUBMITTER_TEXT1}, {tag: QUAY, value: CERTAINTY_ASSESSMENT-2}]}, {tag: SOUR, children: [{tag: TEXT, value: TEXT_FROM_SOURCE10}, {tag: OBJE, ref: D-12}, {tag: OBJE, children: [{tag: TITL, value: DESCRIPTIVE_TITLE3}, {tag: FORM, value: MULTIMEDIA_FORMAT3, children: [{tag: MEDI, value: SOURCE_MEDIA_TYPE3}]}, {tag: FILE, value: MULTIMEDIA_FILE_REFN3}]}, {tag: NOTE, ref: N-2}, {tag: NOTE, value: SUBMITTER_TEXT2}, {tag: QUAY, value: CERTAINTY_ASSESSMENT-12}]}, {tag: OBJE, ref: D-13}, {tag: OBJE, children: [{tag: TITL, value: DESCRIPTIVE_TITLE1}, {tag: FORM, value: MULTIMEDIA_FORMAT1, children: [{tag: MEDI, value: SOURCE_MEDIA_TYPE1}]}, {tag: FILE, value: MULTIMEDIA_FILE_REFN1}]}]", origin.getIndividuals().get(0).toString());

		final Transformation<Gedcom, Flef> t = new IndividualTransformation();
		t.to(origin, destination);

		Assertions.assertEquals("id: I1, tag: INDIVIDUAL, children: [{tag: NAME, children: [{tag: TYPE, value: NAME_TYPE}, {tag: TITLE, value: NAME_PIECE_PREFIX1}, {tag: PERSONAL_NAME, value: NAME_PIECE_GIVEN1, children: [{tag: NAME_SUFFIX, value: NAME_PIECE_SUFFIX1}]}, {tag: INDIVIDUAL_NICKNAME, value: NAME_PIECE_NICKNAME1}, {tag: FAMILY_NAME, value: NAME_PIECE_SURNAME_PREFIX1 NAME_PIECE_SURNAME1}, {tag: NOTE, ref: N-10}, {tag: NOTE, ref: N1}, {tag: SOURCE, ref: S2, children: [{tag: CREDIBILITY, value: CERTAINTY_ASSESSMENT11}]}, {tag: PHONETIC, children: [{tag: TYPE, value: PHONETIC_TYPE}, {tag: TITLE, value: NAME_PIECE_PREFIX2}, {tag: PERSONAL_NAME, value: NAME_PIECE_GIVEN2, children: [{tag: NAME_SUFFIX, value: NAME_PIECE_SUFFIX2}]}, {tag: INDIVIDUAL_NICKNAME, value: NAME_PIECE_NICKNAME2}, {tag: FAMILY_NAME, value: NAME_PIECE_SURNAME_PREFIX2 NAME_PIECE_SURNAME2}, {tag: NOTE, ref: N-9}, {tag: NOTE, ref: N4}, {tag: SOURCE, ref: S4, children: [{tag: CREDIBILITY, value: CERTAINTY_ASSESSMENT12}]}]}, {tag: TRANSCRIPTION, children: [{tag: TYPE, value: ROMANIZED_TYPE}, {tag: TITLE, value: NAME_PIECE_PREFIX3}, {tag: PERSONAL_NAME, value: NAME_PIECE_GIVEN3, children: [{tag: NAME_SUFFIX, value: NAME_PIECE_SUFFIX3}]}, {tag: INDIVIDUAL_NICKNAME, value: NAME_PIECE_NICKNAME3}, {tag: FAMILY_NAME, value: NAME_PIECE_SURNAME_PREFIX3 NAME_PIECE_SURNAME3}, {tag: NOTE, ref: N-8}, {tag: NOTE, ref: N6}, {tag: SOURCE, ref: S6, children: [{tag: CREDIBILITY, value: CERTAINTY_ASSESSMENT13}]}]}]}, {tag: SEX, value: SEX_VALUE}, {tag: FAMILY_CHILD, ref: F2, children: [{tag: PEDIGREE, children: [{tag: PARENT1, value: PEDIGREE_LINKAGE_TYPE}, {tag: PARENT2, value: PEDIGREE_LINKAGE_TYPE}]}, {tag: CERTAINTY, value: CHILD_LINKAGE_STATUS}, {tag: NOTE, ref: N-8}, {tag: NOTE, ref: N6}]}, {tag: FAMILY_SPOUSE, children: [{tag: NOTE, ref: N-7}, {tag: NOTE, ref: N8}]}, {tag: ASSOCIATION, ref: I4, children: [{tag: RELATIONSHIP, value: RELATION_IS_DESCRIPTOR}, {tag: NOTE, ref: N-4}, {tag: NOTE, ref: N9}, {tag: SOURCE, ref: S7, children: [{tag: PAGE, value: WHERE_WITHIN_SOURCE}, {tag: ROLE, value: ROLE_IN_EVENT}, {tag: CREDIBILITY, value: CERTAINTY_ASSESSMENT5}]}, {tag: SOURCE, ref: S9, children: [{tag: CREDIBILITY, value: CERTAINTY_ASSESSMENT6}]}]}, {tag: ALIAS, ref: I2}, {tag: ALIAS, ref: I3}, {tag: EVENT, value: BIRTH, children: [{tag: TYPE, value: EVENT_OR_FACT_CLASSIFICATION1}, {tag: DATE, value: DATE_VALUE1}, {tag: PLACE, ref: P1}, {tag: AGENCY, value: RESPONSIBLE_AGENCY1}, {tag: CAUSE, value: CAUSE_OF_EVENT1}, {tag: NOTE, ref: N-12}, {tag: SOURCE, ref: S10}, {tag: SOURCE, ref: D-4}, {tag: RESTRICTION, value: RESTRICTION_NOTICE1}, {tag: FAMILY_CHILD, ref: F3}]}, {tag: EVENT, value: ADOPTION, children: [{tag: TYPE, value: EVENT_OR_FACT_CLASSIFICATION4}, {tag: DATE, value: DATE_VALUE4}, {tag: PLACE, ref: P2}, {tag: AGENCY, value: RESPONSIBLE_AGENCY4}, {tag: CAUSE, value: CAUSE_OF_EVENT4}, {tag: NOTE, ref: N-12}, {tag: SOURCE, ref: S10}, {tag: SOURCE, ref: D-7}, {tag: RESTRICTION, value: RESTRICTION_NOTICE4}, {tag: FAMILY_CHILD, ref: F4, children: [{tag: ADOPTED_BY, value: ADOPTED_BY_WHICH_PARENT}]}]}, {tag: EVENT, value: DEATH, children: [{tag: TYPE, value: EVENT_OR_FACT_CLASSIFICATION2}, {tag: DATE, value: DATE_VALUE2}, {tag: PLACE, ref: P3}, {tag: AGENCY, value: RESPONSIBLE_AGENCY2}, {tag: CAUSE, value: CAUSE_OF_EVENT2}, {tag: NOTE, ref: N-13}, {tag: SOURCE, ref: S10}, {tag: SOURCE, ref: D-5}, {tag: RESTRICTION, value: RESTRICTION_NOTICE2}]}, {tag: EVENT, value: BURIAL, children: [{tag: TYPE, value: EVENT_OR_FACT_CLASSIFICATION3}, {tag: DATE, value: DATE_VALUE3}, {tag: PLACE, ref: P4}, {tag: AGENCY, value: RESPONSIBLE_AGENCY3}, {tag: CAUSE, value: CAUSE_OF_EVENT3}, {tag: NOTE, ref: N-13}, {tag: SOURCE, ref: S10}, {tag: SOURCE, ref: D-6}, {tag: RESTRICTION, value: RESTRICTION_NOTICE3}]}, {tag: ATTRIBUTE, value: CHARACTERISTIC, children: [{tag: VALUE, value: CHARACTERISTIC}, {tag: TYPE, value: EVENT_OR_FACT_CLASSIFICATION5}, {tag: PLACE, ref: P5}, {tag: AGENCY, value: RESPONSIBLE_AGENCY5}, {tag: CAUSE, value: CAUSE_OF_EVENT5}, {tag: RESTRICTION, value: RESTRICTION_NOTICE5}, {tag: NOTE, ref: N-12}, {tag: SOURCE, ref: S10}, {tag: SOURCE, ref: D-8}]}, {tag: ATTRIBUTE, value: RESIDENCE, children: [{tag: TYPE, value: EVENT_OR_FACT_CLASSIFICATION6}]}, {tag: NOTE, ref: N-3}, {tag: NOTE, ref: N12}, {tag: SOURCE, ref: S11, children: [{tag: PAGE, value: WHERE_WITHIN_SOURCE}, {tag: ROLE, value: ROLE_IN_EVENT}, {tag: CREDIBILITY, value: CERTAINTY_ASSESSMENT-2}]}, {tag: SOURCE, ref: S12, children: [{tag: CREDIBILITY, value: CERTAINTY_ASSESSMENT-12}]}, {tag: SOURCE, ref: D-13}, {tag: SOURCE, ref: S13}, {tag: FILE, value: MULTIMEDIA_FILE_REFN1}, {tag: RESTRICTION, value: RESTRICTION_NOTICE}]", destination.getIndividuals().get(0).toString());
		Assertions.assertEquals("id: P1, tag: PLACE, children: [{tag: ADDRESS, value: ADDRESS_LINE1 - ADDRESS_LINE1 - ADDRESS_LINE11 - ADDRESS_LINE12 - ADDRESS_LINE13}, {tag: CITY, value: ADDRESS_CITY1}, {tag: STATE, value: ADDRESS_STATE1}, {tag: COUNTRY, value: ADDRESS_COUNTRY1}, {tag: MAP, children: [{tag: LATITUDE, value: PLACE_LATITUDE1}, {tag: LONGITUDE, value: PLACE_LONGITUDE1}]}, {tag: NOTE, ref: N-12}]", destination.getPlaces().get(0).toString());
		Assertions.assertEquals("id: P2, tag: PLACE, children: [{tag: ADDRESS, value: ADDRESS_LINE4 - ADDRESS_LINE4 - ADDRESS_LINE41 - ADDRESS_LINE42 - ADDRESS_LINE43}, {tag: CITY, value: ADDRESS_CITY4}, {tag: STATE, value: ADDRESS_STATE4}, {tag: COUNTRY, value: ADDRESS_COUNTRY4}, {tag: MAP, children: [{tag: LATITUDE, value: PLACE_LATITUDE4}, {tag: LONGITUDE, value: PLACE_LONGITUDE4}]}, {tag: NOTE, ref: N-12}]", destination.getPlaces().get(1).toString());
		Assertions.assertEquals("id: P3, tag: PLACE, children: [{tag: ADDRESS, value: ADDRESS_LINE2 - ADDRESS_LINE2 - ADDRESS_LINE21 - ADDRESS_LINE22 - ADDRESS_LINE23}, {tag: CITY, value: ADDRESS_CITY2}, {tag: STATE, value: ADDRESS_STATE2}, {tag: COUNTRY, value: ADDRESS_COUNTRY2}, {tag: MAP, children: [{tag: LATITUDE, value: PLACE_LATITUDE2}, {tag: LONGITUDE, value: PLACE_LONGITUDE2}]}, {tag: NOTE, ref: N-12}]", destination.getPlaces().get(2).toString());
		Assertions.assertEquals("id: P4, tag: PLACE, children: [{tag: ADDRESS, value: ADDRESS_LINE3 - ADDRESS_LINE3 - ADDRESS_LINE31 - ADDRESS_LINE32 - ADDRESS_LINE33}, {tag: CITY, value: ADDRESS_CITY3}, {tag: STATE, value: ADDRESS_STATE3}, {tag: COUNTRY, value: ADDRESS_COUNTRY3}, {tag: MAP, children: [{tag: LATITUDE, value: PLACE_LATITUDE3}, {tag: LONGITUDE, value: PLACE_LONGITUDE3}]}, {tag: NOTE, ref: N-12}]", destination.getPlaces().get(3).toString());
		Assertions.assertEquals("id: P5, tag: PLACE, children: [{tag: ADDRESS, value: ADDRESS_LINE5 - ADDRESS_LINE5 - ADDRESS_LINE51 - ADDRESS_LINE52 - ADDRESS_LINE53}, {tag: CITY, value: ADDRESS_CITY5}, {tag: STATE, value: ADDRESS_STATE5}, {tag: COUNTRY, value: ADDRESS_COUNTRY5}, {tag: MAP, children: [{tag: LATITUDE, value: PLACE_LATITUDE5}, {tag: LONGITUDE, value: PLACE_LONGITUDE5}]}, {tag: NOTE, ref: N-12}]", destination.getPlaces().get(4).toString());
	}

	@Test
	void from(){
		final GedcomNode individual = transformerFrom.create("INDIVIDUAL")
			.withID("I1")
			.addChild(transformerFrom.create("NAME")
				.addChild(transformerFrom.create("TYPE")
					.withValue("NAME_TYPE")
					.addChildReference("FAMILY", "F1")
						.addChildValue("TYPE", "EVENT_OR_FACT_CLASSIFICATION_NAME")
				)
				.addChildValue("LOCALE", "en-US")
				.addChildValue("TITLE", "TITLE_PIECE1")
				.addChild(transformerFrom.create("PERSONAL_NAME")
					.withValue("NAME_PIECE1")
					.addChildValue("NAME_SUFFIX", "NAME_PIECE_SUFFIX1")
				)
				.addChildValue("INDIVIDUAL_NICKNAME", "NAME_PIECE_NICKNAME1")
				.addChildValue("FAMILY_NAME", "SURNAME_PIECE1")
				.addChildValue("FAMILY_NICKNAME", "SURNAME_PIECE_NICKNAME1")
				.addChild(transformerFrom.create("PHONETIC")
					.addChildValue("TITLE", "TITLE_PIECE2")
					.addChild(transformerFrom.create("PERSONAL_NAME")
						.withValue("NAME_PIECE2")
						.addChildValue("NAME_SUFFIX", "NAME_PIECE_SUFFIX2")
					)
					.addChildValue("INDIVIDUAL_NICKNAME", "NAME_PIECE_NICKNAME2")
					.addChildValue("FAMILY_NAME", "SURNAME_PIECE2")
					.addChildValue("FAMILY_NICKNAME", "SURNAME_PIECE_NICKNAME2")
				)
				.addChild(transformerFrom.create("TRANSCRIPTION")
					.withValue("TRANSCRIPTION_TYPE")
					.addChildValue("SYSTEM", "TRANSCRIPTION_SYSTEM")
					.addChildValue("TITLE", "TITLE_PIECE3")
					.addChild(transformerFrom.create("PERSONAL_NAME")
						.withValue("NAME_PIECE3")
						.addChildValue("NAME_SUFFIX", "NAME_PIECE_SUFFIX3")
					)
					.addChildValue("INDIVIDUAL_NICKNAME", "NAME_PIECE_NICKNAME3")
					.addChildValue("FAMILY_NAME", "SURNAME_PIECE3")
					.addChildValue("FAMILY_NICKNAME", "SURNAME_PIECE_NICKNAME3")
				)
				.addChildReference("NOTE", "N1")
				.addChildReference("SOURCE", "S1")
			)
			.addChildValue("SEX", "SEX_VALUE")
			.addChild(transformerFrom.create("FAMILY_CHILD")
				.addChild(transformerFrom.create("PEDIGREE")
					.addChildValue("PARENT1", "PEDIGREE_LINKAGE_TYPE1")
					.addChildValue("PARENT2", "PEDIGREE_LINKAGE_TYPE2")
				)
				.addChildValue("CERTAINTY", "CERTAINTY")
				.addChildValue("CREDIBILITY", "CREDIBILITY_ASSESSMENT")
				.addChildReference("CULTURAL_RULE", "A1")
				.addChildReference("NOTE", "N1")
			)
			.addChild(transformerFrom.create("FAMILY_SPOUSE")
				.addChildReference("CULTURAL_RULE", "A1")
				.addChildReference("NOTE", "N2")
			)
			.addChild(transformerFrom.create("ASSOCIATION")
				.withXRef("I1")
				.addChildValue("TYPE", "ASSOCIATION_TYPE")
				.addChildValue("RELATIONSHIP", "RELATION_IS_DESCRIPTOR")
				.addChildReference("NOTE", "N1")
				.addChildReference("SOURCE", "S1")
			)
			.addChild(transformerFrom.create("ALIAS")
				.withXRef("I1")
				.addChildReference("NOTE", "N2")
			)
			.addChild(transformerFrom.create("EVENT")
				.withValue("BIRTH")
				.addChildValue("TYPE", "EVENT_OR_FACT_CLASSIFICATION_BIRTH")
				.addChild(transformerFrom.create("DATE")
					.withValue("DATE_TIME_VALUE")
					.addChildValue("CALENDAR", "CALENDAR_TYPE")
					.addChildValue("CREDIBILITY", "CREDIBILITY_ASSESSMENT")
				)
				.addChild(transformerFrom.create("PLACE")
					.withXRef("P1")
					.addChildValue("CERTAINTY", "CERTAINTY_ASSESSMENT")
					.addChildValue("CREDIBILITY", "CREDIBILITY_ASSESSMENT")
				)
				.addChildValue("AGENCY", "RESPONSIBLE_AGENCY")
				.addChild(transformerFrom.create("CAUSE")
					.withValue("CAUSE_OF_EVENT")
					.addChildValue("CERTAINTY", "CERTAINTY_ASSESSMENT")
					.addChildValue("CREDIBILITY", "CREDIBILITY_ASSESSMENT")
				)
				.addChild(transformerFrom.create("GROUP")
					.withXRef("G1")
					.addChildValue("ROLE", "ROLE_IN_GROUP")
					.addChildReference("NOTE", "N1")
					.addChildValue("CREDIBILITY", "CREDIBILITY_ASSESSMENT")
					.addChildValue("RESTRICTION", "RESTRICTION_NOTICE")
				)
				.addChildReference("CULTURAL_RULE", "A1")
				.addChildReference("NOTE", "N1")
				.addChildReference("SOURCE", "S1")
				.addChildValue("CERTAINTY", "CERTAINTY_ASSESSMENT")
				.addChildValue("CREDIBILITY", "CREDIBILITY_ASSESSMENT")
				.addChildValue("RESTRICTION", "RESTRICTION_NOTICE")
				.addChildReference("FAMILY_CHILD", "F1")
			)
			.addChild(transformerFrom.create("EVENT")
				.withValue("ADOPTION")
				.addChildValue("TYPE", "EVENT_OR_FACT_CLASSIFICATION_ADOPTION")
				.addChild(transformerFrom.create("FAMILY_CHILD")
					.withXRef("F1")
					.addChildValue("ADOPTED_BY", "ADOPTED_BY_WHICH_PARENT")
				)
			)
			.addChild(transformerFrom.create("EVENT")
				.withValue("DEATH")
				.addChildValue("TYPE", "EVENT_OR_FACT_CLASSIFICATION_DEATH")
			)
			.addChild(transformerFrom.create("ATTRIBUTE")
				.withValue("CASTE")
				.addChildValue("VALUE", "CASTE_NAME")
				.addChildValue("TYPE", "EVENT_OR_FACT_CLASSIFICATION_CASTE")
			)
			.addChild(transformerFrom.create("ATTRIBUTE")
				.withValue("CHARACTERISTIC")
				.addChildValue("VALUE", "CHARACTERISTIC")
				.addChild(transformerFrom.create("KEY")
					.withValue("KEY_DESCRIPTION1")
					.addChildValue("VALUE", "VALUE_DESCRIPTION1")
					.addChildValue("CERTAINTY", "CERTAINTY_ASSESSMENT")
					.addChildValue("CREDIBILITY", "CREDIBILITY_ASSESSMENT")
					.addChildReference("CULTURAL_RULE", "A1")
				)
				.addChild(transformerFrom.create("KEY")
					.withValue("KEY_DESCRIPTION2")
					.addChildValue("VALUE", "VALUE_DESCRIPTION2")
				)
				.addChildValue("TYPE", "EVENT_OR_FACT_CLASSIFICATION_ATTR1")
			)
			.addChild(transformerFrom.create("ATTRIBUTE")
				.withValue("RESIDENCE")
				.addChildValue("TYPE", "EVENT_OR_FACT_CLASSIFICATION_ATTR2")
			)
			.addChildReference("CULTURAL_RULE", "A1")
			.addChildReference("NOTE", "N2")
			.addChildValue("SOURCE", "S1")
			.addChildValue("RESTRICTION", "RESTRICTION_NOTICE");
		final Flef origin = new Flef();
		origin.addIndividual(individual);
		origin.addNote(transformerFrom.createWithIDValue("NOTE", "N1", "SUBMITTER_TEXT1"));
		origin.addNote(transformerFrom.createWithIDValue("NOTE", "N2", "SUBMITTER_TEXT2"));
		origin.addSource(transformerFrom.createWithID("SOURCE", "S1"));
		origin.addPlace(transformerFrom.createWithID("PLACE", "P1"));
		origin.addCulturalRule(transformerFrom.createWithID("CULTURAL_RULE", "A1"));
		origin.addGroup(transformerFrom.createWithID("GROUP", "G1"));
		final Gedcom destination = new Gedcom();

		Assertions.assertEquals("id: I1, tag: INDIVIDUAL, children: [{tag: NAME, children: [{tag: TYPE, value: NAME_TYPE, children: [{tag: FAMILY, ref: F1}, {tag: TYPE, value: EVENT_OR_FACT_CLASSIFICATION_NAME}]}, {tag: LOCALE, value: en-US}, {tag: TITLE, value: TITLE_PIECE1}, {tag: PERSONAL_NAME, value: NAME_PIECE1, children: [{tag: NAME_SUFFIX, value: NAME_PIECE_SUFFIX1}]}, {tag: INDIVIDUAL_NICKNAME, value: NAME_PIECE_NICKNAME1}, {tag: FAMILY_NAME, value: SURNAME_PIECE1}, {tag: FAMILY_NICKNAME, value: SURNAME_PIECE_NICKNAME1}, {tag: PHONETIC, children: [{tag: TITLE, value: TITLE_PIECE2}, {tag: PERSONAL_NAME, value: NAME_PIECE2, children: [{tag: NAME_SUFFIX, value: NAME_PIECE_SUFFIX2}]}, {tag: INDIVIDUAL_NICKNAME, value: NAME_PIECE_NICKNAME2}, {tag: FAMILY_NAME, value: SURNAME_PIECE2}, {tag: FAMILY_NICKNAME, value: SURNAME_PIECE_NICKNAME2}]}, {tag: TRANSCRIPTION, value: TRANSCRIPTION_TYPE, children: [{tag: SYSTEM, value: TRANSCRIPTION_SYSTEM}, {tag: TITLE, value: TITLE_PIECE3}, {tag: PERSONAL_NAME, value: NAME_PIECE3, children: [{tag: NAME_SUFFIX, value: NAME_PIECE_SUFFIX3}]}, {tag: INDIVIDUAL_NICKNAME, value: NAME_PIECE_NICKNAME3}, {tag: FAMILY_NAME, value: SURNAME_PIECE3}, {tag: FAMILY_NICKNAME, value: SURNAME_PIECE_NICKNAME3}]}, {tag: NOTE, ref: N1}, {tag: SOURCE, ref: S1}]}, {tag: SEX, value: SEX_VALUE}, {tag: FAMILY_CHILD, children: [{tag: PEDIGREE, children: [{tag: PARENT1, value: PEDIGREE_LINKAGE_TYPE1}, {tag: PARENT2, value: PEDIGREE_LINKAGE_TYPE2}]}, {tag: CERTAINTY, value: CERTAINTY}, {tag: CREDIBILITY, value: CREDIBILITY_ASSESSMENT}, {tag: CULTURAL_RULE, ref: A1}, {tag: NOTE, ref: N1}]}, {tag: FAMILY_SPOUSE, children: [{tag: CULTURAL_RULE, ref: A1}, {tag: NOTE, ref: N2}]}, {tag: ASSOCIATION, ref: I1, children: [{tag: TYPE, value: ASSOCIATION_TYPE}, {tag: RELATIONSHIP, value: RELATION_IS_DESCRIPTOR}, {tag: NOTE, ref: N1}, {tag: SOURCE, ref: S1}]}, {tag: ALIAS, ref: I1, children: [{tag: NOTE, ref: N2}]}, {tag: EVENT, value: BIRTH, children: [{tag: TYPE, value: EVENT_OR_FACT_CLASSIFICATION_BIRTH}, {tag: DATE, value: DATE_TIME_VALUE, children: [{tag: CALENDAR, value: CALENDAR_TYPE}, {tag: CREDIBILITY, value: CREDIBILITY_ASSESSMENT}]}, {tag: PLACE, ref: P1, children: [{tag: CERTAINTY, value: CERTAINTY_ASSESSMENT}, {tag: CREDIBILITY, value: CREDIBILITY_ASSESSMENT}]}, {tag: AGENCY, value: RESPONSIBLE_AGENCY}, {tag: CAUSE, value: CAUSE_OF_EVENT, children: [{tag: CERTAINTY, value: CERTAINTY_ASSESSMENT}, {tag: CREDIBILITY, value: CREDIBILITY_ASSESSMENT}]}, {tag: GROUP, ref: G1, children: [{tag: ROLE, value: ROLE_IN_GROUP}, {tag: NOTE, ref: N1}, {tag: CREDIBILITY, value: CREDIBILITY_ASSESSMENT}, {tag: RESTRICTION, value: RESTRICTION_NOTICE}]}, {tag: CULTURAL_RULE, ref: A1}, {tag: NOTE, ref: N1}, {tag: SOURCE, ref: S1}, {tag: CERTAINTY, value: CERTAINTY_ASSESSMENT}, {tag: CREDIBILITY, value: CREDIBILITY_ASSESSMENT}, {tag: RESTRICTION, value: RESTRICTION_NOTICE}, {tag: FAMILY_CHILD, ref: F1}]}, {tag: EVENT, value: ADOPTION, children: [{tag: TYPE, value: EVENT_OR_FACT_CLASSIFICATION_ADOPTION}, {tag: FAMILY_CHILD, ref: F1, children: [{tag: ADOPTED_BY, value: ADOPTED_BY_WHICH_PARENT}]}]}, {tag: EVENT, value: DEATH, children: [{tag: TYPE, value: EVENT_OR_FACT_CLASSIFICATION_DEATH}]}, {tag: ATTRIBUTE, value: CASTE, children: [{tag: VALUE, value: CASTE_NAME}, {tag: TYPE, value: EVENT_OR_FACT_CLASSIFICATION_CASTE}]}, {tag: ATTRIBUTE, value: CHARACTERISTIC, children: [{tag: VALUE, value: CHARACTERISTIC}, {tag: KEY, value: KEY_DESCRIPTION1, children: [{tag: VALUE, value: VALUE_DESCRIPTION1}, {tag: CERTAINTY, value: CERTAINTY_ASSESSMENT}, {tag: CREDIBILITY, value: CREDIBILITY_ASSESSMENT}, {tag: CULTURAL_RULE, ref: A1}]}, {tag: KEY, value: KEY_DESCRIPTION2, children: [{tag: VALUE, value: VALUE_DESCRIPTION2}]}, {tag: TYPE, value: EVENT_OR_FACT_CLASSIFICATION_ATTR1}]}, {tag: ATTRIBUTE, value: RESIDENCE, children: [{tag: TYPE, value: EVENT_OR_FACT_CLASSIFICATION_ATTR2}]}, {tag: CULTURAL_RULE, ref: A1}, {tag: NOTE, ref: N2}, {tag: SOURCE, value: S1}, {tag: RESTRICTION, value: RESTRICTION_NOTICE}]", origin.getIndividuals().get(0).toString());
		Assertions.assertEquals("id: N1, tag: NOTE, value: SUBMITTER_TEXT1", origin.getNotes().get(0).toString());
		Assertions.assertEquals("id: N2, tag: NOTE, value: SUBMITTER_TEXT2", origin.getNotes().get(1).toString());
		Assertions.assertEquals("id: S1, tag: SOURCE", origin.getSources().get(0).toString());
		Assertions.assertEquals("id: A1, tag: CULTURAL_RULE", origin.getCulturalRules().get(0).toString());
		Assertions.assertEquals("id: G1, tag: GROUP", origin.getGroups().get(0).toString());
		Assertions.assertEquals("id: P1, tag: PLACE", origin.getPlaces().get(0).toString());

		final Transformation<Gedcom, Flef> t = new IndividualTransformation();
		t.from(origin, destination);

		Assertions.assertEquals("id: I1, tag: INDI, children: [{tag: RESN, value: RESTRICTION_NOTICE}, {tag: NAME, value: TITLE_PIECE1 NAME_PIECE1 NAME_PIECE_SUFFIX1, children: [{tag: TYPE, value: NAME_TYPE}, {tag: NPFX, value: TITLE_PIECE1}, {tag: GIVN, value: NAME_PIECE1}, {tag: NSFX, value: NAME_PIECE_SUFFIX1}, {tag: FONE, value: TITLE_PIECE2 NAME_PIECE2 NAME_PIECE_SUFFIX2, children: [{tag: NPFX, value: TITLE_PIECE2}, {tag: GIVN, value: NAME_PIECE2}, {tag: NSFX, value: NAME_PIECE_SUFFIX2}]}, {tag: ROMN, value: TITLE_PIECE3 NAME_PIECE3 NAME_PIECE_SUFFIX3, children: [{tag: NPFX, value: TITLE_PIECE3}, {tag: GIVN, value: NAME_PIECE3}, {tag: NSFX, value: NAME_PIECE_SUFFIX3}]}, {tag: NOTE, ref: N1}, {tag: SOUR, ref: S1}]}, {tag: SEX, value: SEX_VALUE}, {tag: FAMC, children: [{tag: PEDI, value: PARENT1: PEDIGREE_LINKAGE_TYPE1, PARENT2: PEDIGREE_LINKAGE_TYPE2}, {tag: STAT, value: CERTAINTY}, {tag: NOTE, ref: N1}]}, {tag: FAMS, children: [{tag: NOTE, ref: N2}]}, {tag: ASSO, ref: I1, children: [{tag: TYPE, value: ASSOCIATION_TYPE}, {tag: RELA, value: RELATION_IS_DESCRIPTOR}, {tag: NOTE, ref: N1}, {tag: SOUR, ref: S1}]}, {tag: ALIA, ref: I1, children: [{tag: NOTE, ref: N2}]}, {tag: BIRT, children: [{tag: TYPE, value: EVENT_OR_FACT_CLASSIFICATION_BIRTH}, {tag: DATE, value: DATE_TIME_VALUE}, {tag: AGNC, value: RESPONSIBLE_AGENCY}, {tag: CAUS, value: CAUSE_OF_EVENT}, {tag: RESN, value: RESTRICTION_NOTICE}, {tag: FAMC, ref: F1}, {tag: NOTE, ref: N1}, {tag: SOUR, ref: S1}]}, {tag: ADOP, children: [{tag: TYPE, value: EVENT_OR_FACT_CLASSIFICATION_ADOPTION}, {tag: FAMC, ref: F1, children: [{tag: ADOP, value: ADOPTED_BY_WHICH_PARENT}]}]}, {tag: DEAT, children: [{tag: TYPE, value: EVENT_OR_FACT_CLASSIFICATION_DEATH}]}, {tag: CAST, value: CASTE, children: [{tag: TYPE, value: EVENT_OR_FACT_CLASSIFICATION_CASTE}]}, {tag: DSCR, value: CHARACTERISTIC, children: [{tag: TYPE, value: EVENT_OR_FACT_CLASSIFICATION_ATTR1}]}, {tag: RESI, value: RESIDENCE, children: [{tag: TYPE, value: EVENT_OR_FACT_CLASSIFICATION_ATTR2}]}, {tag: FACT, value: _FAMILY_NICKNAME, children: [{tag: TYPE, value: Family Nickname}]}, {tag: NOTE, ref: N2}]", destination.getIndividuals().get(0).toString());
	}

}